// apps/web/app/api/public/qsc/[token]/pdf/route.ts
import React from "react";
import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import ReactPDF, {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// ---------------------------
// TYPES
// ---------------------------

type QscResultRow = {
  id: string;
  token: string;
  full_name?: string | null;
  email?: string | null;
  org_name?: string | null;
  primary_personality?: string | null;
  secondary_personality?: string | null;
  primary_mindset?: string | null;
  secondary_mindset?: string | null;
  created_at?: string | null;
  [key: string]: any;
};

// ---------------------------
// SUPABASE
// ---------------------------

function createSupabaseClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
  const key =
    process.env.SUPABASE_SERVICE_ROLE_KEY ||
    process.env.SUPABASE_ANON_KEY!;

  return createClient(url, key, { db: { schema: "portal" } });
}

// ---------------------------
// PDF STYLES + DOCUMENT
// ---------------------------

const styles = StyleSheet.create({
  page: {
    padding: 32,
    fontSize: 12,
    fontFamily: "Helvetica",
  },
  title: {
    fontSize: 20,
    marginBottom: 12,
  },
  subtitle: {
    fontSize: 14,
    marginBottom: 8,
  },
  line: {
    marginBottom: 4,
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 32,
    right: 32,
    textAlign: "center",
    fontSize: 10,
  },
});

const QscLeadersDocument = ({ result }: { result: QscResultRow | null }) => (
  <Document
    title="QSC Leaders Report"
    author="MindCanvas"
  >
    <Page size="A4" style={styles.page}>
      <Text style={styles.title}>
        Quantum Source Code — Leaders Report
      </Text>

      <Text style={styles.line}>
        {(result?.full_name || "Anonymous Leader") +
          " — " +
          (result?.org_name || "Organisation")}
      </Text>

      <Text style={styles.subtitle}>Snapshot</Text>

      <Text style={styles.line}>
        Name: {result?.full_name || "N/A"}
      </Text>
      <Text style={styles.line}>
        Email: {result?.email || "N/A"}
      </Text>
      <Text style={styles.line}>
        Organisation: {result?.org_name || "N/A"}
      </Text>

      <Text style={styles.line}>
        Primary Personality: {result?.primary_personality || "N/A"}
      </Text>
      <Text style={styles.line}>
        Secondary Personality: {result?.secondary_personality || "N/A"}
      </Text>

      <Text style={styles.line}>
        Primary Mindset: {result?.primary_mindset || "N/A"}
      </Text>
      <Text style={styles.line}>
        Secondary Mindset: {result?.secondary_mindset || "N/A"}
      </Text>

      <Text style={styles.line}>
        Created At:{" "}
        {result?.created_at
          ? new Date(result.created_at).toLocaleString("en-GB")
          : "N/A"}
      </Text>

      <Text style={styles.footer}>
        Generated by MindCanvas — Quantum Source Code Leaders
      </Text>
    </Page>
  </Document>
);

// ---------------------------
// ROUTE HANDLER
// ---------------------------

export async function GET(
  _req: Request,
  { params }: { params: { token: string } }
) {
  const token = params.token;

  if (!token) {
    return NextResponse.json(
      { ok: false, error: "Missing token" },
      { status: 400 }
    );
  }

  try {
    const sb = createSupabaseClient();

    const { data: result, error } = await sb
      .from("qsc_results")
      .select("*")
      .eq("token", token)
      .single<QscResultRow>();

    if (error) {
      console.error("Failed to load QSC result:", error);
    }

    const pdfStream = await ReactPDF.renderToStream(
      <QscLeadersDocument result={result ?? null} />
    );

    // Cast to any to satisfy TS, Next will stream this fine in Node runtime
    return new NextResponse(pdfStream as any, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `inline; filename="qsc-leaders-${token}.pdf"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (err: any) {
    console.error("Unexpected QSC PDF error", err);

    return NextResponse.json(
      { ok: false, error: "Failed to generate PDF" },
      { status: 500 }
    );
  }
}



