// apps/web/app/api/admin/orgs/[orgId]/provision-pack/route.ts
import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { ORG_TEMPLATE_PACKS } from '@/lib/orgTemplatePacks';

function supaAdmin() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY!;
  return createClient(url, key, { db: { schema: 'portal' } });
}

export async function POST(
  req: Request,
  { params }: { params: { orgId: string } },
) {
  const body = await req.json();
  const { packId } = body as { packId: string };

  // TODO: super-admin auth check

  const pack = ORG_TEMPLATE_PACKS.find((p) => p.id === packId);
  if (!pack) {
    return NextResponse.json(
      { error: 'Unknown template pack' },
      { status: 400 },
    );
  }

  const supa = supaAdmin();

  // 1) Resolve template org
  const { data: templateOrg, error: templateOrgError } = await supa
    .from('orgs')
    .select('id, slug')
    .eq('slug', pack.templateOrgSlug)
    .single();

  if (templateOrgError || !templateOrg) {
    console.error('Template org error', templateOrgError);
    return NextResponse.json(
      { error: 'Template org not found' },
      { status: 500 },
    );
  }

  const newOrgId = params.orgId;

  // 2) Fetch template tests to clone
  const { data: templateTests, error: testsError } = await supa
    .from('tests')
    .select('*')
    .eq('org_id', templateOrg.id)
    .in('slug', pack.templateTestSlugs);

  if (testsError || !templateTests || templateTests.length === 0) {
    console.error('Template tests error', testsError);
    return NextResponse.json(
      { error: 'No template tests found for pack' },
      { status: 500 },
    );
  }

  const createdTests: any[] = [];

  for (const t of templateTests) {
    // 3) Insert new test row for the target org
    const { data: inserted, error: insertError } = await supa
      .from('tests')
      .insert({
        // new id will be generated by default if you use default uuid
        org_id: newOrgId,
        name: t.name,
        slug: t.slug,
        // if you added description: description: t.description,
        // include any other relevant fields used in your app:
        // type: t.type,
        is_active: true,
        framework_id: t.framework_id,
        report_template_id: t.report_template_id,
        brand_override: t.brand_override,
      })
      .select('*')
      .single();

    if (insertError || !inserted) {
      console.error('Insert cloned test error', insertError);
      continue;
    }

    createdTests.push(inserted);

    const newTestId = inserted.id;

    // 4) Clone questions if they are per-test
    const { data: templateQuestions, error: questionsError } = await supa
      .from('test_questions')
      .select('*')
      .eq('test_id', t.id);

    if (!questionsError && templateQuestions && templateQuestions.length) {
      const clonedQuestions = templateQuestions.map((q) => ({
        test_id: newTestId,
        idx: q.idx,
        question: q.question,
        type: q.type,
        options: q.options,
        profile_map: q.profile_map,
      }));

      const { error: insertQError } = await supa
        .from('test_questions')
        .insert(clonedQuestions);

      if (insertQError) {
        console.error('Clone questions error', insertQError);
      }
    }

    // 5) Seed a test_link
    const { data: link, error: linkError } = await supa
      .from('test_links')
      .insert({
        test_id: newTestId,
        token: crypto.randomUUID().replace(/-/g, '').slice(0, 12),
        max_uses: null,
        use_count: 0,
      })
      .select('*')
      .single();

    if (linkError) {
      console.error('Seed test link error', linkError);
    }
  }

  return NextResponse.json({ tests: createdTests });
}
